### ISSUE TITLE
Switch Manager - Blueprint for the remote

### ISSUE THREAD

**Issue by nervous-inhuman** [ebinf/lightbar2mqtt#8]
Sorry for creating an issue, but I wasn't sure where else to put this, as I wouldn't want to add it to the readme unless the author thought it was a good idea.

---

For anyone else using Switch Manager in Home Assistant, I've made a blueprint for the Light Bar remote:

```
name: Mi Computer Monitor Light Bar Remote control
service: custom
event_type: mqtt
mqtt_topic_format: lightbar2mqtt/+/+/state
buttons:
  - actions:
      - title: press
        conditions:
          - key: payload
            value: press 
      - title: rotate left
        conditions:
          - key: payload
            value: turn_counterclockwise
      - title: rotate right
        conditions:
          - key: payload
            value: turn_clockwise
      - title: rotate left (pressed)
        conditions:
          - key: payload
            value: press_turn_counterclockwise
      - title: rotate right (pressed)
        conditions:
          - key: payload
            value: press_turn_clockwise
```

And the picture for it:
https://github.com/user-attachments/assets/62bbb335-ce04-41a3-9a95-b43588586a2e

Here's how it looks in the Switch Manager:

![Image](https://github.com/user-attachments/assets/b6ae8d42-cc5e-4517-a94a-fed206a0c9ac)

The instructions on how to "install" the blueprint can be found here:
https://github.com/Sian-Lee-SA/Home-Assistant-Switch-Manager?tab=readme-ov-file#blueprints
